#!/usr/bin/env bash
# Build Astrolabe and install it as a background service:
# systemd --user on Linux, a launchd LaunchAgent on macOS.
set -euo pipefail
cd "$(dirname "$0")"

echo "── bridge deps"
(cd bridge && npm install --no-fund --no-audit)

echo "── web build"
(cd web && npm install --no-fund --no-audit && npm run build)

if [ "$(uname)" = "Darwin" ]; then
  # launchd starts agents with a bare PATH, so bake in the absolute node
  # path found right now (Node ≥ 22.18 for unflagged type stripping).
  NODE="$(command -v node)"
  PLIST=~/Library/LaunchAgents/dev.d3s.astrolabe.plist
  LOGDIR=~/Library/Logs
  mkdir -p ~/Library/LaunchAgents "$LOGDIR"
  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>dev.d3s.astrolabe</string>
  <key>ProgramArguments</key>
  <array>
    <string>${NODE}</string>
    <string>$(pwd)/bridge/main.ts</string>
  </array>
  <key>WorkingDirectory</key><string>$(pwd)/bridge</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <!-- Without this the bridge is a background job subject to App Nap, and
       macOS stretches its timers when the machine is idle — exactly when a
       phone is most likely to be checking on a long-running agent. The
       endpoint re-claim, WS keepalive and CPU sampler all ride those. -->
  <key>ProcessType</key><string>Interactive</string>
  <!-- Don't respawn in a tight loop if node itself is broken. -->
  <key>ThrottleInterval</key><integer>10</integer>
  <!-- ~/Library/Logs, not /tmp: macOS prunes /tmp periodically, which
       silently eats the log you need after an unattended failure. -->
  <key>StandardOutPath</key><string>${LOGDIR}/astrolabe.log</string>
  <key>StandardErrorPath</key><string>${LOGDIR}/astrolabe.log</string>
</dict>
</plist>
EOF
  launchctl bootout "gui/$(id -u)/dev.d3s.astrolabe" 2>/dev/null || true
  launchctl bootstrap "gui/$(id -u)" "$PLIST"
  sleep 2
  port="${ASTROLABE_PORT:-7979}"
  ip="$(tailscale ip -4 2>/dev/null | head -1 || /Applications/Tailscale.app/Contents/MacOS/Tailscale ip -4 2>/dev/null | head -1 || true)"
  echo
  echo "astrolabe is up (launchd): http://${ip:-<tailscale-ip>}:${port}"
  echo "logs: ${LOGDIR}/astrolabe.log"
  # launchd has no EnvironmentFile= equivalent, so the bridge reads this
  # file itself (see loadEnvFile in bridge/main.ts) — that, not the plist,
  # is where ASTROLABE_APNS_* and ASTROLABE_HOST belong.
  echo "env:  ~/.config/astrolabe/env  (ASTROLABE_APNS_*, ASTROLABE_HOST)"
  echo
  echo "note: a LaunchAgent only runs once someone is logged in. For a Mac"
  echo "      you control remotely, enable automatic login so a reboot"
  echo "      brings the bridge back without anyone at the keyboard."
  exit 0
fi

echo "── migrating config/state from the old scry name, if present"
if [ -d ~/.config/scry ] && [ ! -d ~/.config/astrolabe ]; then
  cp -r ~/.config/scry ~/.config/astrolabe
  echo "   copied ~/.config/scry -> ~/.config/astrolabe"
fi
if [ -d ~/.local/state/scry ] && [ ! -d ~/.local/state/astrolabe ]; then
  cp -r ~/.local/state/scry ~/.local/state/astrolabe
  echo "   copied ~/.local/state/scry -> ~/.local/state/astrolabe"
fi

echo "── retiring the old scry.service unit, if enabled"
if systemctl --user list-unit-files scry.service &>/dev/null; then
  systemctl --user disable --now scry.service 2>/dev/null || true
  rm -f ~/.config/systemd/user/scry.service
  systemctl --user daemon-reload
fi

echo "── systemd unit"
# Generated (not copied) so ExecStart/WorkingDirectory point at THIS
# checkout and node — the static astrolabe.service is only a commented
# template. Same approach as the launchd plist above.
NODE="$(command -v node)"
mkdir -p ~/.config/systemd/user
cat > ~/.config/systemd/user/astrolabe.service <<EOF
# astrolabe — phone bridge for the zodiac agent multiplexer.
# Generated by install.sh from $(pwd) — re-run it after moving the checkout.
[Unit]
Description=astrolabe — zodiac phone bridge
After=network-online.target

[Service]
Type=simple
Environment=PATH=$(dirname "$NODE"):/usr/local/bin:/usr/bin:/bin
# Port/session/host overrides and APNs push credentials (ASTROLABE_*):
EnvironmentFile=-%h/.config/astrolabe/env
ExecStart=${NODE} $(pwd)/bridge/main.ts
WorkingDirectory=$(pwd)/bridge
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
EOF
systemctl --user daemon-reload
systemctl --user enable --now astrolabe.service
sleep 2
systemctl --user --no-pager status astrolabe.service | head -5 || true

port="${ASTROLABE_PORT:-7979}"
ip="$(tailscale ip -4 2>/dev/null | head -1 || true)"
echo
echo "astrolabe is up: http://${ip:-<tailscale-ip>}:${port}"
echo "open it on your phone (same tailnet), add to home screen."
